[project]
name = "epub-translate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argostranslate>=1.9.6",
    "beautifulsoup4>=4.13.3",
    "ebooklib>=0.18",
    "tqdm>=4.67.1",
    "transformers>=4.49.0",
]
